{% set name = "bmi-fortran" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - pkg-config [osx]
  host:
    - libgfortran
  run:
    - {{ compiler('fortran') }}
    - libgfortran

test:
  commands:
    - run_heatf
    - run_bmiheatf

about:
  home: https://csdms.colorado.edu/wiki/BMI_Description
  license: MIT
  summary:
    Fortran bindings, created with Fortran 2003, for the Basic Model Interface.
  dev_url: https://github.com/csdms/bmi-fortran
