{% set name = "bmi-fortran" %}
{% set version = "1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
  run:
    - {{ compiler('fortran') }}

about:
  home: https://bmi.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary:
    Fortran bindings, created with Fortran 2003, for the Basic Model Interface.
  dev_url: https://github.com/csdms/bmi-fortran
