language: generic
os:
  - linux
  - osx
env:
  matrix:
    - TRAVIS_PYTHON_VERSION="3.*"
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install python=$TRAVIS_PYTHON_VERSION
  - conda install gfortran_$TRAVIS_OS_NAME-64 cmake
  - source activate root
install:
  - mkdir _build && cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release
  - make
  - make install
script:
  - test -f $CONDA_PREFIX/include/bmif_1_2.mod
  - test -h $CONDA_PREFIX/lib/libbmif$SHLIB_EXT
