name: Build and Test

on: [push, pull_request]

env:
  BMI_VERSION: 2_0

jobs:
  build-test-unix:

    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    env:
      SHLIB_EXT: ${{ matrix.os == 'ubuntu-latest' && '.so' || '.dylib' }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
 
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: testing
          create-args: >-
            make
            cmake
            pkg-config
            fortran-compiler

      - name: Configure project
        run: |
          cmake -B _build -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release

      - name: Build and install
        run: cmake --build _build --target install --config Release

      - name: Test
        run: |
          test -f $CONDA_PREFIX/include/bmif_$BMI_VERSION.mod
          test -s $CONDA_PREFIX/lib/libbmif.a
          test -h $CONDA_PREFIX/lib/libbmif${{ env.SHLIB_EXT }}
          pkg-config --exists --print-errors bmif

  build-test-windows:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: windows-latest

    env:
      LIBRARY_PREFIX: $env:CONDA_PREFIX\Library

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: testing
          create-args: >-
            cmake
            pkg-config
            cxx-compiler
            fortran-compiler
          init-shell: >-
            powershell

      - name: Set the FC environment variable to the Fortran conda compiler
        run: |
          echo "FC=$CONDA_PREFIX/Library/bin/flang-new.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure, build, and install project
        run: |
          cmake -B _build -G Ninja -DCMAKE_INSTALL_PREFIX="${{ env.LIBRARY_PREFIX }}" -DCMAKE_BUILD_TYPE=Release
          cmake --build _build --target install --config Release

      - name: Check (for humans)
        run: |
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\bmif.lib
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\bin\bmif.dll
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\include\bmif_${{ env.BMI_VERSION }}.mod
          Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\bmif_static.lib
          pkg-config --exists --print-errors bmif

      - name: Test (for machines)
        run: |
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\bmif.lib ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\bin\bmif.dll ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\include\bmif_${{ env.BMI_VERSION }}.mod ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\bmif_static.lib ) ){ exit 1 }
          if ( -not ( Test-Path -Path ${{ env.LIBRARY_PREFIX }}\lib\pkgconfig\bmif.pc ) ){ exit 1 }
