name: Build and Test

on: [push, pull_request]

jobs:
  build-test-unix:

    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    env:
      BMI_VERSION: 2_0

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
 
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: testing
          create-args: >-
            make
            cmake
            fortran-compiler
            mamba

      - name: Make cmake build directory
        run: cmake -E make_directory build

      - name: Configure cmake
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --target install --config Release

      - name: Test
        run: |
          test -f $CONDA_PREFIX/include/bmif_$BMI_VERSION.mod
          test -s $CONDA_PREFIX/lib/libbmif.a

      - name: Test (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: test -h $CONDA_PREFIX/lib/libbmif.so

      - name: Test (macOS)
        if: matrix.os == 'macos-latest'
        run: test -h $CONDA_PREFIX/lib/libbmif.dylib
